### PR TITLE
Add rule no-dead-urls and progress spinner

### LINKED ISSUE #19: Detect 404s and 301s
Can this actually poll the links? I'm not sure how it would work on PRs (since problems can appear on existing content) but it can be a great way to keep lists up to date.

### PR DESCRIPTION
**Pull request by transitive-bullshit**
Fixes #19.

Incorporates work from https://github.com/davidtheclark/remark-lint-no-dead-urls/pull/7 and [check-links](https://github.com/transitive-bullshit/check-links).

This PR checks all URLs in an awesome list for **liveness**.

It is very fast compared with previous alternatives, but in order to do this robustly, it still throttles the maximum concurrency and thus adds a non-trivial amount of execution time, especially for larger lists. To mitigate this, I've added an `ora` spinner to represent progress.

demo

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Perhaps we should say the url is unreachable instead of dead.

👍 

> Currently, check-links is just using the got defaults for all requests (with a custom user-agent). Are there any additional got options that you'd recommend enabling to increase robustness?

Not that I can think of. It should already have good defaults.

> Further discussion and follow-up work should probably take place in check-links.

Sure, I'll open an issue.

**Comment by sindresorhus** [comment]
I figured out the issue. It's a problem with Node.js 8, that is fixed in Node.js 10.

See: https://github.com/nodejs/node/issues/16196

In Node.js 8, `require('got')('https://blog.dcpos.ch/how-to-make-your-electron-app-sexy')` caused an error:

```
RequestError: write EPROTO 140735592387456:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
```

That no longer happens in Node.js 10, so consider this issue fixed and we should not do anything further.

**Comment by carlosperate** [comment]
Is this feature included on 0.6.0? 
I'm seeing a lot of false positives with node v10.9.0 in Travis-CI.
To compare, I am also running awesome_bot, and it doesn't have issues accessing the links (I've also manually test them and they are not dead).

**Comment by sindresorhus** [comment]
Which of the links are you saying are false positives?

**Comment by carlosperate** [comment]
So from https://travis-ci.org/carlosperate/awesome-microbit/builds/423808998
It shows these as dead links:

  ✖  181:3    Link to https://wiki.forth-ev.de/doku.php/en:projects:microbit:start is dead                                               no-dead-urls
  ✖  182:3    Link to http://wiki.freepascal.org/micro:bit is dead                                                                       no-dead-urls
  ✖  191:3    Link to http://www.kodugamelab.com/bbc-microbit/ is dead                                                                   no-dead-urls
  ✖  329:3    Link to http://www.i-programmer.info/programming/hardware/9654-offline-cc-development-with-the-microbit-.html is dead      no-dead-urls
  ✖  364:3    Link to http://sparkfuneducation.com/video-resources/microbit.html is dead                                                 no-dead-urls
  ✖  396:3    Link to http://www.kodugamelab.com/resources/#microbit is dead                                                             no-dead-urls
  ✖  440:3    Link to https://www.element14.com/community/servlet/JiveServlet/downloadBody/87638-102-3-368412/microbit24x15.pdf is dead  no-dead-urls

These are **all** false positives.
Down the log it can be seen as well that awesome_bot can access all links:
```
Checking URLs: ✓✓✓→✓→→✓→✓✓→→✓✓→→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓→✓✓✓✓✓✓✓✓✓→✓→→→→✓✓✓→✓→→→✓✓✓✓→→✓✓✓✓→✓✓✓✓✓✓→✓✓✓✓→✓→✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓→✓→→✓✓✓✓→✓→✓✓✓✓✓✓✓✓→→✓✓✓✓✓→→✓✓✓✓✓✓✓✓✓→✓✓✓→→✓→✓→✓✓✓→→✓✓✓✓✓→→→→✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓→→✓✓✓✓✓✓✓✓✓✓✓
No issues :-)
```

**Comment by transitive-bullshit** [comment]
@carlosperate thanks for the report 💯 -- I'm sure we can figure out what's going on and make `awesome-lint` report these correctly. Let's move this discussion over to #42.

**Pull request merged**
